spring:
        datasource:
                url: jdbc:postgresql://localhost:5432/Citron
                username: postgres
                password: astayoucode
        jpa:
                hibernate:
                        ddl-auto: update
                show-sql: true
                properties:
                        hibernate:
                                format_sql: true

# Enable Liquibase
        spring.liquibase.enabled=true
  
  # Set the path to the changelog file
        spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
